POST http://localhost:4000/api/v1/auth/refresh
Content-Type: application/json

# {
#     "email": "test4@example.com",
#     "password": "12345ad"
# }

{
    "refresh_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZjE2ODQ3Yi1jOWNjLTQxZDEtOGVlOS01MjEyM2NmY2Y5MDciLCJpYXQiOjE3MzU4MTM3MDQsImV4cCI6MTczNTgxNDYwNH0.RhcWBcuv09zhZrHnSdNTyktLLE1nhj3I8IhArdxHL7y9Dak8OjpGWWBFaeg1MagzNR06LGaFq6SUM71ujUZ2bYaU4xxiyZgoTwF0PSrDxic4gPbTv2gr2zjLICJSDs-m-fjMly2wCrkafsKKj7kQiTv1mlprcQRv5uPiSKAo_VUNrpU9OtXpKYYRstgAAXbMPc1S-Fi_mVrMr-mv25DuufyzzZz6dE0opLYNBSwaqpDoMBXxmu3JGAFlQolwZ3uP3k_YT7R-mDU5B2EDDRygzeySM4lPbAX-_DVbPFjL_07SCv3fwHDcmWMZ44IL4ygXjvdwtxBlwe3ecBhFJ97FLA"
}
