GET http://localhost:4000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZjE2ODQ3Yi1jOWNjLTQxZDEtOGVlOS01MjEyM2NmY2Y5MDciLCJpYXQiOjE3MzU4MjAwNjUsImV4cCI6MTczNTgyMDk2NX0.baJYVnGBnBLwZm8ZhsYn0ATEgqWewrq6lD_Fior93OuE0e7cXzrJuOITNN-JQzIYq7XKRrOdzKb4JpCCX5n2CbRwtWG5moZdSDyoOJeOthixSbUFLQGdpQdCEx811D1upvinjp0xNaGg94haerpi0u92iL-nRnLLQbAUwOVEjIrAdbkX1d0ta_5xdbyiMhykO-wvWLdGyGElTX6dKBiYjxFYZ6UYaxJbTumLB2FShs5H6a81-n69ECg_i7QQCABY8i017yWKbVWbIquVrc6ctRy5idYtKe0RVuteFF80h2uHHOmpyQgnUQk1nG4luXgxeiYjqCbM3khExBcCNm5BSw
Content-Type: application/json

# {
#     "email": "test4@example.com",
#     "password": "12345ad"
# }

# {
#     "refresh_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZjE2ODQ3Yi1jOWNjLTQxZDEtOGVlOS01MjEyM2NmY2Y5MDciLCJpYXQiOjE3MzU4MTU2NTcsImV4cCI6MTczNTgxNjU1N30.gs10QXvpJSQgOs2dL-d20z8fbEdX0bhMrmmNPuBWUS3NE0J78bBpeqol8oBcjlT6eAP0eFS08Ma864ldVuPXAa5oAQ5zjLNCzFheESpBc3fVPrDceqcud3Co9IisFmCMLGIyZ0kYURdEH2SjcbOP5w_oCoPFJWoaxsR-0Axu8L__erHe2kW37MhpPlvgTb9yNeNqTOIZkOkaiFU2tlLZDhafVFewQF8dIrtWKNYSaQV14rEgqY58iqHlXB-EuI0qdy9X0dYD1BHKsXfpJCkMbcPdwHc24jbreAqkujAV4K-MCmeO-_brmwUtShXrtpqXSddwc-6f9Fnga9fDBeFBWQ"
# }

